name: running around

on:
  workflow_dispatch:
  schedule:
    - cron: "17 03 12 11 0"

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT_WITH_WORKFLOW_SCOPE }}

    - name: Make script executable
      run: chmod +x main.sh

    - name: Run Bash script
      id: script-output
      run: |
        output=$(./main.sh "${{ secrets.BOT_TOKEN }}" "inputJson.json")
        echo "::set-output name=script_output::$output"

    - name: Use the output
      run: |
        echo "The script output is: ${{ steps.script-output.outputs.script_output }}"

    - name: Set cron schedule
      run: |
        sed -i '0,/cron: ".*"/s/cron: ".*"/cron: "${{ steps.script-output.outputs.script_output }}"/' .github/workflows/runner.yml

    - name: Commit readme
      uses: EndBug/add-and-commit@v9
      with:
        add: '.github/workflows/runner.yml' 
        message: 'update workflow'
        push: true
