name: running around

on:
  workflow_dispatch:
  schedule:
    - cron: "48 * * * *"

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Make script executable
      run: chmod +x main.sh

    - name: Run Bash script
      id: script-output
      run: |
        output=$(./main.sh "${{ secrets.BOT_TOKEN }}" "inputJson.json")
        echo "::set-output name=script_output::$output"

    - name: Use the output
      run: |
        echo "The script output is: ${{ steps.script-output.outputs.script_output }}"

    - name: Set cron schedule
      run: |
        sed '/^- cron: /s/"[^"]*"/"${{ steps.script-output.outputs.script_output }}"/' .github/workflows/runner.yml

    - name: Commit and push changes
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add .github/workflows/runner.yml
        git commit -m "Update cron value"
        git push
      env:
        GH_PAT: ${{ secrets.PAT_WITH_WORKFLOW_SCOPE }}
