name: running around

on:
  workflow_dispatch:
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Bash script
      id: script-output
      run: |
        output=$(./main.sh "${{ secrets.BOT_TOKEN }}" "inputJson.json")
        echo "::set-output name=script_output::$output"

    - name: Use the output
      run: |
        echo "The script output is: ${{ steps.script-output.outputs.script_output }}"
