name: running around

on:
  schedule:
    - cron: "29 21 * * *"

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Make script executable
      run: chmod +x main.sh

    - name: Run Bash script
      id: script-output
      run: |
        output=$(./main.sh "${{ secrets.BOT_TOKEN }}" "inputJson.json")
        echo "::set-output name=script_output::$output"

    - name: Use the output
      run: |
        echo "The script output is: ${{ steps.script-output.outputs.script_output }}"

    - uses: gr2m/set-cron-schedule-action@v2
      with:
          token: ${{ secrets.PAT_WITH_WORKFLOW_SCOPE }}
          cron: |
            ${{ steps.script-output.outputs.script_output }}
          workflow: runner.yml
