name: Release
on:
  workflow_dispatch:
    inputs: 
      version:
        required: true
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Configure Git
        run: git config --global core.autocrlf false
      - name: Checkout branch
        uses: actions/checkout@v4
      - name: Update le version
        run: jq --arg newVersion "${{ github.event.inputs.version }}" '.batVersion = $newVersion' "inputJson.json" > inputJson.json
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          add: 'inputJson.json' 
          message: 'chore: Release ${{ github.event.inputs.version }}'
          tag: ${{ github.event.inputs.version }} 
          push: true